//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KamillaSagdieva320_.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> ID_Action { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
